apiVersion: v1
kind: Service
metadata:
  name: uda-capstone-service
spec:
  selector:
    app: uda-capstone-webapp
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uda-capstone-deployment
spec:
  selector:
    matchLabels:
      app: uda-capstone-webapp
  replicas: 2
  template:
    metadata:
      labels:
        app: uda-capstone-webapp
    spec:
      containers:
      - name: uda-capstone
        image: nikhilsarecha/uda-capstone:latest
        ports:
        - containerPort: 80